//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitemaUnicesumar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresenceStudent
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int PresenceRegisterClassId { get; set; }
        public bool WasPresent { get; set; }
        public string Description { get; set; }
    
        public virtual PresenceRegisterClass PresenceRegisterClass { get; set; }
        public virtual Student Student { get; set; }
    }
}
